"""
Core AUTOSAR model classes - base infrastructure and fundamental modules.

Implements: SWR_CORE_00001 (Core model organization)
"""

from eb_model.models.core.abstract import (
    EcucObject,
    EcucEnumerationParamDef,
    EcucParamConfContainerDef,
    EcucRefType,
    Version,
    Module,
)
from eb_model.models.core.eb_doc import AbstractModel, EBModel, PreferenceModel
from eb_model.models.core.importer_xdm import SystemDescriptionImporter
from eb_model.models.core.os_xdm import (
    OsAlarmAction,
    OsAlarmAutostart,
    OsAlarmActivateTask,
    OsAlarmCallback,
    OsAlarmIncrementCounter,
    OsAlarmSetEvent,
    OsAlarm,
    OsApplicationHooks,
    OsApplicationTrustedFunction,
    OsAppMode,
    OsApplication,
    OsDriver,
    OsTimeConstant,
    OsCounter,
    OsResource,
    OsIsrResourceLock,
    OsIsrTimingProtection,
    OsIsr,
    OsTaskAutostart,
    OsTaskResourceLock,
    OsTaskTimingProtection,
    OsTask,
    OsScheduleTableAutostart,
    OsScheduleTblAdjustableExpPoint,
    OsScheduleTableTaskActivation,
    OsScheduleTableEventSetting,
    OsScheduleTableExpiryPoint,
    OsScheduleTable,
    MkMemoryRegion,
    MkMemoryProtection,
    MkFunction,
    MkStack,
    MkThreadCustomization,
    MkOptimization,
    OsMicrokernel,
    CommonPublishedInformation,
    PublishedInformation,
    OsHwIncrementer,
    OsEvent,
    OsSpinlock,
    OsPeripheralArea,
    OsOS,
    OsHooks,
    OsCoreConfig,
    OsAutosarCustomization,
    Os,
)
from eb_model.models.core.rte_xdm import (
    RteBswGeneral,
    RteBswEventToIsrMapping,
    RteBswExclusiveAreaImpl,
    RteBswExternalTriggerConfig,
    RteBswInternalTriggerConfig,
    RteBswRequiredModeGroupConnection,
    RteBswRequiredSenderReceiverConnection,
    RteBswRequiredClientServerConnection,
    RteBswRequiredTriggerConnection,
    RteGeneration,
    ComTaskConfiguration,
    BswConfiguration,
    OsCounterAssignments,
    CooperativeTasks,
    TaskChain,
    RteImplicitCommunication,
    RteInitializationBehavior,
    RteInitializationRunnableBatch,
    RteOsInteraction,
    RteModeToScheduleTableMapping,
    RteRips,
    DataMappings,
    RteExclusiveAreaImplementation,
    RteExternalTriggerConfig,
    RteInternalTriggerConfig,
    RteNvRamAllocation,
    RteSwComponentType,
    RteEventToIsrMapping,
    AbstractEventToTaskMapping,
    RteEventToTaskMapping,
    RteEventToTaskMappingV3,
    RteEventToTaskMappingV4,
    RteBswEventToTaskMapping,
    RteBswEventToTaskMappingV3,
    RteBswEventToTaskMappingV4,
    AbstractRteInstance,
    RteSwComponentInstance,
    RteBswModuleInstance,
    Rte,
)
from eb_model.models.core.tm_xdm import TmGeneral, TmInterruptSynchronization, TmTickTime, TmTrigger, Tm
from eb_model.models.core.pbcfgm_xdm import PbcfgMProtectionSet, PbcfgMCoreProtectionSet, PbcfgMGeneral, PbcfgM
from eb_model.models.core.ecum_xdm import (
    EcuMCommonConfiguration,
    EcuMDefaultShutdownTarget,
    EcuMDriverInitItem,
    EcuMDriverInitListOne,
    EcuMDriverInitListZero,
    EcuMDriverRestartList,
    EcuMSleepMode,
    EcuMWakeupSource,
    EcuMDemEventParameterRefs,
    EcuMFixedConfiguration,
    EcuMDriverInitListThree,
    EcuMDriverInitListTwo,
    EcuMFixedUserConfig,
    EcuMTTII,
    EcuMWdgM,
    EcuMFlexConfiguration,
    EcuMAlarmClock,
    EcuMFlexUserConfig,
    EcuMGoDownAllowedUsers,
    EcuMResetMode,
    EcuMSetClockAllowedUsers,
    EcuMShutdownCause,
    EcuMShutdownTarget,
    EcuMDefensiveProgramming,
    EcuMFixedGeneral,
    EcuMFlexGeneral,
    EcuMServiceAPI,
    ReportToDem,
    EcuMStartup,
    EcuMShutdown,
    EcuMAlarm,
    EcuMGeneral,
    EcuM,
)
from eb_model.models.core.ecuc_xdm import (
    EcucPartitionSoftwareComponentInstanceRef,
    EcucPartition,
    EcucGeneral,
    EcucHardware,
    EcucCoreDefinition,
    EcucPduCollection,
    MetaDataType,
    MetaDataItem,
    Pdu,
    EcucPduDedicatedPartition,
    EcucPostBuildVariants,
    EcucVariationResolver,
    EcucPartitionCollection,
    EcuC,
)
from eb_model.models.core.det_xdm import (
    DetServiceAPI,
    DetNotification,
    DetDefensiveProgramming,
    SoftwareComponentList,
    InstanceIdList,
    DetErrorHook,
    DetInitError,
    DetGeneral,
    Det,
)
from eb_model.models.core.bswm_xdm import BswMModeCondition, BswMModeDeclaration, BswMGeneral, BswM

__all__ = (
    "EcucObject", "EcucEnumerationParamDef", "EcucParamConfContainerDef", "EcucRefType",
    "Version", "Module", "AbstractModel", "EBModel", "PreferenceModel", "SystemDescriptionImporter",
    "OsAlarmAction", "OsAlarmAutostart", "OsAlarmActivateTask", "OsAlarmCallback",
    "OsAlarmIncrementCounter", "OsAlarmSetEvent", "OsAlarm", "OsApplicationHooks",
    "OsApplicationTrustedFunction", "OsAppMode", "OsApplication", "OsDriver",
    "OsTimeConstant", "OsCounter", "OsResource", "OsIsrResourceLock",
    "OsIsrTimingProtection", "OsIsr", "OsTaskAutostart", "OsTaskResourceLock",
    "OsTaskTimingProtection", "OsTask", "OsScheduleTableAutostart",
    "OsScheduleTblAdjustableExpPoint", "OsScheduleTableTaskActivation",
    "OsScheduleTableEventSetting", "OsScheduleTableExpiryPoint", "OsScheduleTable",
    "MkMemoryRegion", "MkMemoryProtection", "MkFunction", "MkStack",
    "MkThreadCustomization", "MkOptimization", "OsMicrokernel",
    "CommonPublishedInformation", "PublishedInformation", "OsHwIncrementer",
    "OsEvent", "OsSpinlock", "OsPeripheralArea", "OsOS", "OsHooks",
    "OsCoreConfig", "OsAutosarCustomization", "Os",
    "RteBswGeneral", "RteBswEventToIsrMapping", "RteBswExclusiveAreaImpl",
    "RteBswExternalTriggerConfig", "RteBswInternalTriggerConfig",
    "RteBswRequiredModeGroupConnection", "RteBswRequiredSenderReceiverConnection",
    "RteBswRequiredClientServerConnection", "RteBswRequiredTriggerConnection",
    "RteGeneration", "ComTaskConfiguration", "BswConfiguration",
    "OsCounterAssignments", "CooperativeTasks", "TaskChain",
    "RteImplicitCommunication", "RteInitializationBehavior",
    "RteInitializationRunnableBatch", "RteOsInteraction",
    "RteModeToScheduleTableMapping", "RteRips", "DataMappings",
    "RteExclusiveAreaImplementation", "RteExternalTriggerConfig",
    "RteInternalTriggerConfig", "RteNvRamAllocation", "RteSwComponentType",
    "RteEventToIsrMapping", "AbstractEventToTaskMapping", "RteEventToTaskMapping",
    "RteEventToTaskMappingV3", "RteEventToTaskMappingV4", "RteBswEventToTaskMapping",
    "RteBswEventToTaskMappingV3", "RteBswEventToTaskMappingV4",
    "AbstractRteInstance", "RteSwComponentInstance", "RteBswModuleInstance", "Rte",
    "TmGeneral", "TmInterruptSynchronization", "TmTickTime", "TmTrigger", "Tm",
    "PbcfgMProtectionSet", "PbcfgMCoreProtectionSet", "PbcfgMGeneral", "PbcfgM",
    "EcuMCommonConfiguration", "EcuMDefaultShutdownTarget", "EcuMDriverInitItem",
    "EcuMDriverInitListOne", "EcuMDriverInitListZero", "EcuMDriverRestartList",
    "EcuMSleepMode", "EcuMWakeupSource", "EcuMDemEventParameterRefs",
    "EcuMFixedConfiguration", "EcuMDriverInitListThree", "EcuMDriverInitListTwo",
    "EcuMFixedUserConfig", "EcuMTTII", "EcuMWdgM", "EcuMFlexConfiguration",
    "EcuMAlarmClock", "EcuMFlexUserConfig", "EcuMGoDownAllowedUsers",
    "EcuMResetMode", "EcuMSetClockAllowedUsers", "EcuMShutdownCause",
    "EcuMShutdownTarget", "EcuMDefensiveProgramming", "EcuMFixedGeneral",
    "EcuMFlexGeneral", "EcuMServiceAPI", "ReportToDem", "EcuMStartup",
    "EcuMShutdown", "EcuMAlarm", "EcuMGeneral", "EcuM",
    "EcucPartitionSoftwareComponentInstanceRef", "EcucPartition", "EcucGeneral",
    "EcucHardware", "EcucCoreDefinition", "EcucPduCollection", "MetaDataType",
    "MetaDataItem", "Pdu", "EcucPduDedicatedPartition", "EcucPostBuildVariants",
    "EcucVariationResolver", "EcucPartitionCollection", "EcuC",
    "DetServiceAPI", "DetNotification", "DetDefensiveProgramming",
    "SoftwareComponentList", "InstanceIdList", "DetErrorHook", "DetInitError",
    "DetGeneral", "Det",
    "BswMModeCondition", "BswMModeDeclaration", "BswMGeneral", "BswM",
)
